org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version=0.4.1
maven_group=me.yassigame
archives_name=sablebeyond
enabled_platforms=fabric,neoforge

release_type=alpha
modrinth_project_id=PrW3B4fH
curseforge_project_id=1543480
curseforge_project_slug=sable-beyond

# Minecraft properties
minecraft_version=1.21.1

# Dependencies
fabric_loader_version=0.19.2
fabric_api_version=0.116.11+1.21.1
neoforge_version=21.1.228
mixinextras_version=0.5.3
imguimc_version=1.1.1
cloth_config_version=15.0.140

# Compat / addon dev dependencies
registrate_version=MC1.21-1.3.0+67
veil_version=4.0.0
sable_companion_version=1.6.0
sable_version=1.2.2
jade_version=15.10.4
jade_enabled=false

# - Neoforge only
create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
aronautics_version=1.2.1
aronautics_enabled=true
slice_and_dice_version=4.2.4
slice_and_dice_enabled=true
catalogue_version=6926815
catalogue_enabled=false
kubejs_version=2101.7.2-build.363

# - Fabric only
modmenu_version=11.0.4
modmenu_enabled=true
